// PER IL DATA FETCHING
export const DATA_FETCHING_STARTED = 'DATA_FETCHING_STARTED';
export const DATA_FETCHING_SUCCESS = 'DATA_FETCHING_SUCCESS';
export const DATA_FETCHING_FAIL = 'DATA_FETCHING_FAIL';

//PER IL CARRELLO
export const CART_DELETE_ALL_ITEMS = 'CART_DELETE_ALL_ITEMS';
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM';
export const CART_MINUS_ITEM = 'CART_MINUS_ITEM';
export const CART_MINUS_PLUS = 'CART_MINUS_PLUS';

